---
itamco_Haas:
  startTime: 2017-08-15T06:10Z
  startRUL: 100.0
  startSpindleCap: 1400.0
  startPosCap: 800.0
itamco_DMG:
  startTime: 2017-08-15T06:10Z
  startRUL: 100.0
  startSpindleCap: 4000.0
  startPosCap: 1000.0
